@ApplicationModule(type = ApplicationModule.Type.OPEN)
package com.example.whereabouts.jooq;

// The other classes in this package will be generated by jOOQ.

import org.springframework.modulith.ApplicationModule;